version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    parameters:
      java-version:
        default: 17
        description: |
          The version of OpenJDK to change to
        type: integer
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - run:
          name: Update JDK 17
          command: |-
            #!/bin/bash
                CURRENT_JAVA_VER="$( java -version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1 )"
                CURRENT_JAVAC_VER="$( javac -version 2>&1 | head -1 | cut -f 2- -d ' ' | sed '/^1\./s///' | cut -d'.' -f1 )"
                echo "Current Java Version: $CURRENT_JAVA_VER"
                echo "Current Java Compiler Version : $CURRENT_JAVAC_VER"
                sudo apt-get update && sudo apt-get install openjdk-"${PARAM_JAVA_VER}"-jdk
                sudo update-alternatives --set javac /usr/lib/jvm/java-"${PARAM_JAVA_VER}"-openjdk-amd64/bin/javac
                sudo update-alternatives --set java /usr/lib/jvm/java-"${PARAM_JAVA_VER}"-openjdk-amd64/bin/java
                echo "export JAVA_HOME=/usr/lib/jvm/java-${PARAM_JAVA_VER}-openjdk-amd64" >> ~/.bashrc
                echo "export PATH=$JAVA_HOME/bin:$PATH" >> ~/.bashrc
                NEW_JAVA_VER="$( java -version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1 )"
                NEW_JAVAC_VER="$( javac -version 2>&1 | head -1 | cut -f 2- -d ' ' | sed '/^1\./s///' | cut -d'.' -f1 )"
                echo "New Java Version : $NEW_JAVA_VER"
                echo "New Java Compiler Version : $NEW_JAVAC_VER"
          environment:
            PARAM_JAVA_VER: << parameters.java-version >>
            name: Change OpenJDK version to << parameters.java-version >>
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file